// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package adapter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdapterClient is the client API for Adapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdapterClient interface {
	GiveCompliments(ctx context.Context, in *Name, opts ...grpc.CallOption) (Adapter_GiveComplimentsClient, error)
	RegisterResource(ctx context.Context, in *ResourceSpec, opts ...grpc.CallOption) (*Snapshot, error)
	ConnectToShim(ctx context.Context, in *ShimRequest, opts ...grpc.CallOption) (*ShimResponse, error)
}

type adapterClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterClient(cc grpc.ClientConnInterface) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) GiveCompliments(ctx context.Context, in *Name, opts ...grpc.CallOption) (Adapter_GiveComplimentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[0], "/adapter.Adapter/GiveCompliments", opts...)
	if err != nil {
		return nil, err
	}
	x := &adapterGiveComplimentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Adapter_GiveComplimentsClient interface {
	Recv() (*Compliment, error)
	grpc.ClientStream
}

type adapterGiveComplimentsClient struct {
	grpc.ClientStream
}

func (x *adapterGiveComplimentsClient) Recv() (*Compliment, error) {
	m := new(Compliment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *adapterClient) RegisterResource(ctx context.Context, in *ResourceSpec, opts ...grpc.CallOption) (*Snapshot, error) {
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, "/adapter.Adapter/RegisterResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) ConnectToShim(ctx context.Context, in *ShimRequest, opts ...grpc.CallOption) (*ShimResponse, error) {
	out := new(ShimResponse)
	err := c.cc.Invoke(ctx, "/adapter.Adapter/ConnectToShim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterServer is the server API for Adapter service.
// All implementations must embed UnimplementedAdapterServer
// for forward compatibility
type AdapterServer interface {
	GiveCompliments(*Name, Adapter_GiveComplimentsServer) error
	RegisterResource(context.Context, *ResourceSpec) (*Snapshot, error)
	ConnectToShim(context.Context, *ShimRequest) (*ShimResponse, error)
	mustEmbedUnimplementedAdapterServer()
}

// UnimplementedAdapterServer must be embedded to have forward compatible implementations.
type UnimplementedAdapterServer struct {
}

func (UnimplementedAdapterServer) GiveCompliments(*Name, Adapter_GiveComplimentsServer) error {
	return status.Errorf(codes.Unimplemented, "method GiveCompliments not implemented")
}
func (UnimplementedAdapterServer) RegisterResource(context.Context, *ResourceSpec) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterResource not implemented")
}
func (UnimplementedAdapterServer) ConnectToShim(context.Context, *ShimRequest) (*ShimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectToShim not implemented")
}
func (UnimplementedAdapterServer) mustEmbedUnimplementedAdapterServer() {}

// UnsafeAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterServer will
// result in compilation errors.
type UnsafeAdapterServer interface {
	mustEmbedUnimplementedAdapterServer()
}

func RegisterAdapterServer(s grpc.ServiceRegistrar, srv AdapterServer) {
	s.RegisterService(&Adapter_ServiceDesc, srv)
}

func _Adapter_GiveCompliments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Name)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdapterServer).GiveCompliments(m, &adapterGiveComplimentsServer{stream})
}

type Adapter_GiveComplimentsServer interface {
	Send(*Compliment) error
	grpc.ServerStream
}

type adapterGiveComplimentsServer struct {
	grpc.ServerStream
}

func (x *adapterGiveComplimentsServer) Send(m *Compliment) error {
	return x.ServerStream.SendMsg(m)
}

func _Adapter_RegisterResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).RegisterResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.Adapter/RegisterResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).RegisterResource(ctx, req.(*ResourceSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_ConnectToShim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ConnectToShim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.Adapter/ConnectToShim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ConnectToShim(ctx, req.(*ShimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Adapter_ServiceDesc is the grpc.ServiceDesc for Adapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Adapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adapter.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterResource",
			Handler:    _Adapter_RegisterResource_Handler,
		},
		{
			MethodName: "ConnectToShim",
			Handler:    _Adapter_ConnectToShim_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GiveCompliments",
			Handler:       _Adapter_GiveCompliments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/adapter/adapter.proto",
}
