#!/bin/bash

cd $(dirname $0)
GIT_ROOT=$(git rev-parse --show-toplevel)
cd $GIT_ROOT

# install dependencies
(
    set -x
    cd $HOME
    go get google.golang.org/protobuf/cmd/protoc-gen-go \
        google.golang.org/grpc/cmd/protoc-gen-go-grpc

    go get github.com/cucumber/godog/cmd/godog@v0.11.0

    cd $(mktemp -d)
    curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
    sudo unzip -n protoc-3.15.8-linux-x86_64.zip -x readme.txt -d /usr/local

    sudo apt-wait
    sudo apt update
    sudo apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -sL 'https://getenvoy.io/gpg' | sudo apt-key add -
    apt-key fingerprint 6FF974DB | grep "5270 CEAC"
    yes '\n' | sudo add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable"
    sudo apt update
    sudo apt install -y getenvoy-envoy
)

