#!/bin/bash

cd $(dirname $0)
GIT_ROOT=$(git rev-parse --show-toplevel)
cd $GIT_ROOT

# install dependencies
(
    set -x
    cd $HOME

    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
    go install github.com/cucumber/godog/cmd/godog@v0.11.0

    cd $(mktemp -d)
    curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
    sudo unzip -n protoc-3.15.8-linux-x86_64.zip -x readme.txt -d /usr/local
    sudo chmod 755 /usr/local/bin/protoc

    sudo apt-wait
    sudo apt update
    sudo apt install apt-transport-https gnupg2 curl lsb-release
    curl -sL 'https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key' | sudo gpg --dearmor -o /usr/share/keyrings/getenvoy-keyring.gpg
    echo a077cb587a1b622e03aa4bf2f3689de14658a9497a9af2c427bba5f4cc3c4723 /usr/share/keyrings/getenvoy-keyring.gpg | sha256sum --check
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/getenvoy-keyring.gpg] https://deb.dl.getenvoy.io/public/deb/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/getenvoy.list
    sudo apt update
    sudo apt install -y getenvoy-envoy
)

